include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for AT WebServer
LUCI_DEPENDS:=+at-webserver
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-at-webserver
PKG_VERSION:=3.0.2
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

